refactor stg environment step validation

diff --git a/.github/workflows/promote-verify-ref.yml b/.github/workflows/promote-verify-ref.yml
--- a/.github/workflows/promote-verify-ref.yml
+++ b/.github/workflows/promote-verify-ref.yml
@@ -14,10 +14,12 @@ jobs:
 
     steps:
       - name: Check if branch is main or master for stg
-        if: ${{ github.ref_name != 'main' && github.ref_name != 'master' && inputs.environment == 'stg' }}
+        if: ${{ inputs.environment == 'stg' }}
         run: |
-          echo "Error: Deployment to 'stg' environment is only allowed from 'main' or 'master' branch."
-          exit 1
+          if [[ "${{ github.ref_name }}" != "main" ]] && [[ "${{ github.ref_name }}" != "master" ]]; then
+            echo "Error: Deployment to 'stg' environment is only allowed from 'main' or 'master' branch."
+            exit 1
+          fi
 
       - name: Check if branch name is a valid release tag for prd
         if: ${{ inputs.environment == 'prd' }}
